nome = str(input('coloque seu nome completo: ')).strip()
maiuscula = nome.upper()
print('Seu nome com todas as letras maiúsculas fica: {}'.format(maiuscula))
minuscula = nome.lower()
print('Seu nome com todas as letras minúsculas fica: {}'.format(minuscula))
num_nome = len(nome) - nome.count(' ')
print('Tem no total {} letras esse nome'.format(num_nome))
nome1 = nome.split()
print('Seu 1° nome é {} e ele tem {} letras'.format(nome1[0], len(nome1[0])))